function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = -1000000; // objWorld
	global.__objectDepths[1] = 0; // objCamera
	global.__objectDepths[2] = 0; // objPlayMusic
	global.__objectDepths[3] = 0; // objTitleMenu
	global.__objectDepths[4] = 0; // objDifficultyMenu
	global.__objectDepths[5] = 0; // objOptionsMenu
	global.__objectDepths[6] = 0; // objKeyboardControlsMenu
	global.__objectDepths[7] = 0; // objControllerMenu
	global.__objectDepths[8] = -10; // objPlayerStart
	global.__objectDepths[9] = -10; // objPlayer
	global.__objectDepths[10] = -11; // objBow
	global.__objectDepths[11] = -1; // objBullet
	global.__objectDepths[12] = 0; // objBloodEmitter
	global.__objectDepths[13] = -10; // objBlood
	global.__objectDepths[14] = -100; // objGameOver
	global.__objectDepths[15] = 0; // objYoshiControl
	global.__objectDepths[16] = 0; // objYoshiDead
	global.__objectDepths[17] = -10; // objYoshiLost
	global.__objectDepths[18] = -9; // objTelekid
	global.__objectDepths[19] = 100; // objBlock
	global.__objectDepths[20] = 0; // objBlockDynamic
	global.__objectDepths[21] = 100; // objMiniBlock
	global.__objectDepths[22] = 0; // objSheepBlockB
	global.__objectDepths[23] = 0; // objSheepBlockG
	global.__objectDepths[24] = 0; // objSheepBlockR
	global.__objectDepths[25] = 0; // objSheepBlockY
	global.__objectDepths[26] = 0; // objSheepSpikeB
	global.__objectDepths[27] = 0; // objSheepSpikeG
	global.__objectDepths[28] = 0; // objSheepSpikeR
	global.__objectDepths[29] = 0; // objSheepSpikeY
	global.__objectDepths[30] = 0; // objBoosterBlock
	global.__objectDepths[31] = 0; // objElevatorBlockDown
	global.__objectDepths[32] = 0; // objElevatorBlockUp
	global.__objectDepths[33] = 0; // objDonutBlock
	global.__objectDepths[34] = 0; // objExpandBlockSource
	global.__objectDepths[35] = 0; // objExpandBlock
	global.__objectDepths[36] = 0; // objScalingBlock
	global.__objectDepths[37] = 0; // objPushBlock
	global.__objectDepths[38] = 0; // objBreakableBlock
	global.__objectDepths[39] = 0; // objToggleBlockEmpty
	global.__objectDepths[40] = 0; // objToggleBlockFull
	global.__objectDepths[41] = 0; // objJumpBlockFull
	global.__objectDepths[42] = 0; // objJumpBlockEmpty
	global.__objectDepths[43] = 0; // objSJumpBlockFull
	global.__objectDepths[44] = 0; // objSJumpBlockEmpty
	global.__objectDepths[45] = 100; // objIceBlock
	global.__objectDepths[46] = 0; // objBlockInvis
	global.__objectDepths[47] = 0; // objBlockFake
	global.__objectDepths[48] = 100; // objConveyor
	global.__objectDepths[49] = 100; // objConveyorL
	global.__objectDepths[50] = 100; // objConveyorR
	global.__objectDepths[51] = 1; // objBossBlock
	global.__objectDepths[52] = 0; // objSaveBlocker
	global.__objectDepths[53] = 100; // objSlope
	global.__objectDepths[54] = 100; // objSlopeDownLeft
	global.__objectDepths[55] = 100; // objSlopeDownRight
	global.__objectDepths[56] = 100; // objSlopeUpLeft
	global.__objectDepths[57] = 100; // objSlopeUpRight
	global.__objectDepths[58] = 1; // objPlatform
	global.__objectDepths[59] = 1; // objSidewaysPlatform
	global.__objectDepths[60] = 1; // objPlatformInvisible
	global.__objectDepths[61] = 1; // objPlatformTouch
	global.__objectDepths[62] = 0; // objBalancePlatform
	global.__objectDepths[63] = 0; // objPlayerKiller
	global.__objectDepths[64] = 10; // objSpikeUp
	global.__objectDepths[65] = 10; // objSpikeRight
	global.__objectDepths[66] = 10; // objSpikeLeft
	global.__objectDepths[67] = 10; // objSpikeDown
	global.__objectDepths[68] = 10; // objMiniUp
	global.__objectDepths[69] = 10; // objMiniRight
	global.__objectDepths[70] = 10; // objMiniLeft
	global.__objectDepths[71] = 10; // objMiniDown
	global.__objectDepths[72] = 10; // objLeek
	global.__objectDepths[73] = 0; // objJumpSpikesBehindTiles
	global.__objectDepths[74] = 0; // objJumpSpike
	global.__objectDepths[75] = 0; // objJumpSpike_DownIn
	global.__objectDepths[76] = 0; // objJumpSpike_DownOut
	global.__objectDepths[77] = 0; // objJumpSpike_LeftIn
	global.__objectDepths[78] = 0; // objJumpSpike_LeftOut
	global.__objectDepths[79] = 0; // objJumpSpike_RightIn
	global.__objectDepths[80] = 0; // objJumpSpike_RightOut
	global.__objectDepths[81] = 0; // objJumpSpike_UpIn
	global.__objectDepths[82] = 0; // objJumpSpike_UpOut
	global.__objectDepths[83] = 0; // objToggleSpike
	global.__objectDepths[84] = 0; // objToggleSpike_Down
	global.__objectDepths[85] = 0; // objToggleSpike_DownEmpty
	global.__objectDepths[86] = 0; // objToggleSpike_Left
	global.__objectDepths[87] = 0; // objToggleSpike_LeftEmpty
	global.__objectDepths[88] = 0; // objToggleSpike_Right
	global.__objectDepths[89] = 0; // objToggleSpike_RightEmpty
	global.__objectDepths[90] = 0; // objToggleSpike_Up
	global.__objectDepths[91] = 0; // objToggleSpike_UpEmpty
	global.__objectDepths[92] = 0; // objSwitcherSpike
	global.__objectDepths[93] = 0; // objGreenSpikeDown
	global.__objectDepths[94] = 0; // objGreenSpikeLeft
	global.__objectDepths[95] = 0; // objGreenSpikeRight
	global.__objectDepths[96] = 0; // objGreenSpikeUp
	global.__objectDepths[97] = 0; // objOrangeSpikeDown
	global.__objectDepths[98] = 0; // objOrangeSpikeLeft
	global.__objectDepths[99] = 0; // objOrangeSpikeRight
	global.__objectDepths[100] = 0; // objOrangeSpikeUp
	global.__objectDepths[101] = 0; // objSpikeSwitch
	global.__objectDepths[102] = 0; // objPastelBlackDown
	global.__objectDepths[103] = -1; // objPastelBlackUp
	global.__objectDepths[104] = 0; // objPastelBlueDown
	global.__objectDepths[105] = 0; // objPastelBlueLeft
	global.__objectDepths[106] = 0; // objPastelBlueRight
	global.__objectDepths[107] = 0; // objPastelBlueUp
	global.__objectDepths[108] = 0; // objPastelGreenDown
	global.__objectDepths[109] = 0; // objPastelGreenLeft
	global.__objectDepths[110] = 0; // objPastelGreenRight
	global.__objectDepths[111] = 0; // objPastelGreenUp
	global.__objectDepths[112] = -49; // objPastelGreenWater
	global.__objectDepths[113] = 0; // objPlaceholderBlock
	global.__objectDepths[114] = 0; // objLaser
	global.__objectDepths[115] = 0; // objLaserOffH
	global.__objectDepths[116] = 0; // objLaserOffV
	global.__objectDepths[117] = 0; // objLaserOnH
	global.__objectDepths[118] = 0; // objLaserOnV
	global.__objectDepths[119] = 0; // objLaserSwitch
	global.__objectDepths[120] = 0; // objCLaserOffH
	global.__objectDepths[121] = 0; // objCLaserOffV
	global.__objectDepths[122] = 0; // objCLaserOnH
	global.__objectDepths[123] = 0; // objCLaserOnV
	global.__objectDepths[124] = 0; // objCLaserSwitch
	global.__objectDepths[125] = 0; // objKidBlockDown
	global.__objectDepths[126] = 0; // objKidBlockUp
	global.__objectDepths[127] = 0; // objRedBulletBill
	global.__objectDepths[128] = -1; // objRedBulletCannon
	global.__objectDepths[129] = 100; // objRedBulletHolder
	global.__objectDepths[130] = 0; // objChompTrap
	global.__objectDepths[131] = 1; // objChompy
	global.__objectDepths[132] = 0; // objCherry
	global.__objectDepths[133] = 0; // objCherryBounce
	global.__objectDepths[134] = 0; // objCherryBounceRandom
	global.__objectDepths[135] = 0; // objCherryBounceLat
	global.__objectDepths[136] = 0; // objCherryBounceVert
	global.__objectDepths[137] = -5; // objCherryCircle
	global.__objectDepths[138] = 0; // objCherryNotDestroyOutsideRoom
	global.__objectDepths[139] = 0; // objShurikenRotate
	global.__objectDepths[140] = 0; // objThwomp
	global.__objectDepths[141] = 0; // objKillerBlock
	global.__objectDepths[142] = 0; // objMuncher
	global.__objectDepths[143] = 0; // objSaw
	global.__objectDepths[144] = 0; // objCherryEnemyTest
	global.__objectDepths[145] = 0; // objCherryBossTest
	global.__objectDepths[146] = 10; // objMiku
	global.__objectDepths[147] = 0; // objCherryRandomCol
	global.__objectDepths[148] = 0; // objCherryRandomColExplode
	global.__objectDepths[149] = 0; // objCherryRandomColBounce
	global.__objectDepths[150] = 0; // objTriggerManager
	global.__objectDepths[151] = 0; // objTrigger
	global.__objectDepths[152] = 15; // objTriggerButtonR
	global.__objectDepths[153] = 15; // objTriggerButtonL
	global.__objectDepths[154] = 0; // objFlipBlockDown
	global.__objectDepths[155] = 0; // objFlipBlockUp
	global.__objectDepths[156] = 0; // objHighGravityField
	global.__objectDepths[157] = 0; // objHighSpeedField
	global.__objectDepths[158] = 0; // objLowGravityField
	global.__objectDepths[159] = 0; // objLowSpeedField
	global.__objectDepths[160] = 0; // objAntiGravityField
	global.__objectDepths[161] = 0; // objZeroGravityField
	global.__objectDepths[162] = 0; // objRotateKidDown
	global.__objectDepths[163] = 0; // objRotateKidUp
	global.__objectDepths[164] = 0; // objSpinTransitionPlayer
	global.__objectDepths[165] = 0; // objResetBeam
	global.__objectDepths[166] = 0; // objHighGravBeam
	global.__objectDepths[167] = 0; // objLowGravBeam
	global.__objectDepths[168] = 0; // objSingleJumpBeam
	global.__objectDepths[169] = 0; // objSpeedBeam
	global.__objectDepths[170] = 11; // objVineR
	global.__objectDepths[171] = 11; // objVineL
	global.__objectDepths[172] = 11; // objRiseVineR
	global.__objectDepths[173] = 11; // objRiseVineL
	global.__objectDepths[174] = 11; // objIceVineR
	global.__objectDepths[175] = 11; // objIceVineL
	global.__objectDepths[176] = 11; // objFlipVineR
	global.__objectDepths[177] = 11; // objFlipVineL
	global.__objectDepths[178] = 11; // objStickyVineR
	global.__objectDepths[179] = 11; // objStickyVineL
	global.__objectDepths[180] = 11; // objLowGravVineR
	global.__objectDepths[181] = 11; // objLowGravVineL
	global.__objectDepths[182] = 11; // objTwinWhiteVineR
	global.__objectDepths[183] = 11; // objTwinWhiteVineL
	global.__objectDepths[184] = 11; // objTwinBlackVineR
	global.__objectDepths[185] = 11; // objTwinBlackVineL
	global.__objectDepths[186] = 11; // objSpeedVineR
	global.__objectDepths[187] = 11; // objSpeedVineL
	global.__objectDepths[188] = 0; // objFirePart
	global.__objectDepths[189] = 0; // objShootRefresher
	global.__objectDepths[190] = 0; // objShootRefresherL
	global.__objectDepths[191] = 0; // objShootRefresherR
	global.__objectDepths[192] = 0; // objToggleShootRefresherL
	global.__objectDepths[193] = 0; // objToggleShootRefresherR
	global.__objectDepths[194] = 0; // objDoubleJumpStar
	global.__objectDepths[195] = 0; // objSingleJumpStar
	global.__objectDepths[196] = 0; // objTripleJumpStar
	global.__objectDepths[197] = 0; // objWindField
	global.__objectDepths[198] = -50; // objMagnetField
	global.__objectDepths[199] = 10; // objScreenWrap
	global.__objectDepths[200] = -10; // objScreenWrapFull
	global.__objectDepths[201] = 0; // objDotkidSwap
	global.__objectDepths[202] = 0; // objRoomStartDotkid
	global.__objectDepths[203] = 0; // objVCoinA
	global.__objectDepths[204] = 0; // objVCoinB
	global.__objectDepths[205] = 0; // objRoomStartVPlayer
	global.__objectDepths[206] = 0; // objYoshi
	global.__objectDepths[207] = 0; // objTelekidEnable
	global.__objectDepths[208] = 0; // objTelekidDisable
	global.__objectDepths[209] = 0; // objRoomStartTelekid
	global.__objectDepths[210] = -1000001; // objHPbar
	global.__objectDepths[211] = -1000000; // objHPbar2
	global.__objectDepths[212] = -999999; // objHPbg
	global.__objectDepths[213] = -999998; // objHPside
	global.__objectDepths[214] = -50; // objKeypickControl
	global.__objectDepths[215] = 0; // objKey
	global.__objectDepths[216] = 0; // objMasterKey
	global.__objectDepths[217] = -155; // objDoorBreak
	global.__objectDepths[218] = 0; // objDoor1
	global.__objectDepths[219] = 0; // objDoor2
	global.__objectDepths[220] = 0; // objDoor3
	global.__objectDepths[221] = 0; // objDoor4
	global.__objectDepths[222] = 0; // objDoor6
	global.__objectDepths[223] = 0; // objDoor8
	global.__objectDepths[224] = 0; // objMasterDoor1
	global.__objectDepths[225] = 0; // objMasterDoor2
	global.__objectDepths[226] = 0; // objMasterDoor3
	global.__objectDepths[227] = 0; // objMasterDoor4
	global.__objectDepths[228] = -50; // objWater
	global.__objectDepths[229] = -50; // objWater2
	global.__objectDepths[230] = -50; // objWater3
	global.__objectDepths[231] = -50; // objWaterUnrefreshing
	global.__objectDepths[232] = 0; // objJumpRefresher
	global.__objectDepths[233] = 0; // objBlockRefresher
	global.__objectDepths[234] = -5; // objSign
	global.__objectDepths[235] = 0; // objCouch
	global.__objectDepths[236] = 0; // objLadder
	global.__objectDepths[237] = 0; // objFloatingText
	global.__objectDepths[238] = 0; // objGravityUp
	global.__objectDepths[239] = 0; // objGravityDown
	global.__objectDepths[240] = 0; // objGravityCoinUp
	global.__objectDepths[241] = 0; // objGravityCoinDown
	global.__objectDepths[242] = 0; // objSampleOscillator
	global.__objectDepths[243] = 1; // objSaveMedium
	global.__objectDepths[244] = 1; // objSave
	global.__objectDepths[245] = 1; // objSaveVHard
	global.__objectDepths[246] = 1; // objSaveMediumFlip
	global.__objectDepths[247] = 1; // objSaveFlip
	global.__objectDepths[248] = 1; // objSaveVHardFlip
	global.__objectDepths[249] = 0; // objWarpStart
	global.__objectDepths[250] = 10; // objRoomChanger
	global.__objectDepths[251] = 0; // objWarp
	global.__objectDepths[252] = 0; // objWarpNext
	global.__objectDepths[253] = 10; // objOutsideRoomChanger
	global.__objectDepths[254] = 0; // objColoredWarp
	global.__objectDepths[255] = 0; // objSecretItem
	global.__objectDepths[256] = 0; // objSecretIndicator
	global.__objectDepths[257] = 0; // objBossItem
	global.__objectDepths[258] = 0; // objBossIndicator
	global.__objectDepths[259] = 0; // objGameClear


	global.__objectNames[0] = "objWorld";
	global.__objectNames[1] = "objCamera";
	global.__objectNames[2] = "objPlayMusic";
	global.__objectNames[3] = "objTitleMenu";
	global.__objectNames[4] = "objDifficultyMenu";
	global.__objectNames[5] = "objOptionsMenu";
	global.__objectNames[6] = "objKeyboardControlsMenu";
	global.__objectNames[7] = "objControllerMenu";
	global.__objectNames[8] = "objPlayerStart";
	global.__objectNames[9] = "objPlayer";
	global.__objectNames[10] = "objBow";
	global.__objectNames[11] = "objBullet";
	global.__objectNames[12] = "objBloodEmitter";
	global.__objectNames[13] = "objBlood";
	global.__objectNames[14] = "objGameOver";
	global.__objectNames[15] = "objYoshiControl";
	global.__objectNames[16] = "objYoshiDead";
	global.__objectNames[17] = "objYoshiLost";
	global.__objectNames[18] = "objTelekid";
	global.__objectNames[19] = "objBlock";
	global.__objectNames[20] = "objBlockDynamic";
	global.__objectNames[21] = "objMiniBlock";
	global.__objectNames[22] = "objSheepBlockB";
	global.__objectNames[23] = "objSheepBlockG";
	global.__objectNames[24] = "objSheepBlockR";
	global.__objectNames[25] = "objSheepBlockY";
	global.__objectNames[26] = "objSheepSpikeB";
	global.__objectNames[27] = "objSheepSpikeG";
	global.__objectNames[28] = "objSheepSpikeR";
	global.__objectNames[29] = "objSheepSpikeY";
	global.__objectNames[30] = "objBoosterBlock";
	global.__objectNames[31] = "objElevatorBlockDown";
	global.__objectNames[32] = "objElevatorBlockUp";
	global.__objectNames[33] = "objDonutBlock";
	global.__objectNames[34] = "objExpandBlockSource";
	global.__objectNames[35] = "objExpandBlock";
	global.__objectNames[36] = "objScalingBlock";
	global.__objectNames[37] = "objPushBlock";
	global.__objectNames[38] = "objBreakableBlock";
	global.__objectNames[39] = "objToggleBlockEmpty";
	global.__objectNames[40] = "objToggleBlockFull";
	global.__objectNames[41] = "objJumpBlockFull";
	global.__objectNames[42] = "objJumpBlockEmpty";
	global.__objectNames[43] = "objSJumpBlockFull";
	global.__objectNames[44] = "objSJumpBlockEmpty";
	global.__objectNames[45] = "objIceBlock";
	global.__objectNames[46] = "objBlockInvis";
	global.__objectNames[47] = "objBlockFake";
	global.__objectNames[48] = "objConveyor";
	global.__objectNames[49] = "objConveyorL";
	global.__objectNames[50] = "objConveyorR";
	global.__objectNames[51] = "objBossBlock";
	global.__objectNames[52] = "objSaveBlocker";
	global.__objectNames[53] = "objSlope";
	global.__objectNames[54] = "objSlopeDownLeft";
	global.__objectNames[55] = "objSlopeDownRight";
	global.__objectNames[56] = "objSlopeUpLeft";
	global.__objectNames[57] = "objSlopeUpRight";
	global.__objectNames[58] = "objPlatform";
	global.__objectNames[59] = "objSidewaysPlatform";
	global.__objectNames[60] = "objPlatformInvisible";
	global.__objectNames[61] = "objPlatformTouch";
	global.__objectNames[62] = "objBalancePlatform";
	global.__objectNames[63] = "objPlayerKiller";
	global.__objectNames[64] = "objSpikeUp";
	global.__objectNames[65] = "objSpikeRight";
	global.__objectNames[66] = "objSpikeLeft";
	global.__objectNames[67] = "objSpikeDown";
	global.__objectNames[68] = "objMiniUp";
	global.__objectNames[69] = "objMiniRight";
	global.__objectNames[70] = "objMiniLeft";
	global.__objectNames[71] = "objMiniDown";
	global.__objectNames[72] = "objLeek";
	global.__objectNames[73] = "objJumpSpikesBehindTiles";
	global.__objectNames[74] = "objJumpSpike";
	global.__objectNames[75] = "objJumpSpike_DownIn";
	global.__objectNames[76] = "objJumpSpike_DownOut";
	global.__objectNames[77] = "objJumpSpike_LeftIn";
	global.__objectNames[78] = "objJumpSpike_LeftOut";
	global.__objectNames[79] = "objJumpSpike_RightIn";
	global.__objectNames[80] = "objJumpSpike_RightOut";
	global.__objectNames[81] = "objJumpSpike_UpIn";
	global.__objectNames[82] = "objJumpSpike_UpOut";
	global.__objectNames[83] = "objToggleSpike";
	global.__objectNames[84] = "objToggleSpike_Down";
	global.__objectNames[85] = "objToggleSpike_DownEmpty";
	global.__objectNames[86] = "objToggleSpike_Left";
	global.__objectNames[87] = "objToggleSpike_LeftEmpty";
	global.__objectNames[88] = "objToggleSpike_Right";
	global.__objectNames[89] = "objToggleSpike_RightEmpty";
	global.__objectNames[90] = "objToggleSpike_Up";
	global.__objectNames[91] = "objToggleSpike_UpEmpty";
	global.__objectNames[92] = "objSwitcherSpike";
	global.__objectNames[93] = "objGreenSpikeDown";
	global.__objectNames[94] = "objGreenSpikeLeft";
	global.__objectNames[95] = "objGreenSpikeRight";
	global.__objectNames[96] = "objGreenSpikeUp";
	global.__objectNames[97] = "objOrangeSpikeDown";
	global.__objectNames[98] = "objOrangeSpikeLeft";
	global.__objectNames[99] = "objOrangeSpikeRight";
	global.__objectNames[100] = "objOrangeSpikeUp";
	global.__objectNames[101] = "objSpikeSwitch";
	global.__objectNames[102] = "objPastelBlackDown";
	global.__objectNames[103] = "objPastelBlackUp";
	global.__objectNames[104] = "objPastelBlueDown";
	global.__objectNames[105] = "objPastelBlueLeft";
	global.__objectNames[106] = "objPastelBlueRight";
	global.__objectNames[107] = "objPastelBlueUp";
	global.__objectNames[108] = "objPastelGreenDown";
	global.__objectNames[109] = "objPastelGreenLeft";
	global.__objectNames[110] = "objPastelGreenRight";
	global.__objectNames[111] = "objPastelGreenUp";
	global.__objectNames[112] = "objPastelGreenWater";
	global.__objectNames[113] = "objPlaceholderBlock";
	global.__objectNames[114] = "objLaser";
	global.__objectNames[115] = "objLaserOffH";
	global.__objectNames[116] = "objLaserOffV";
	global.__objectNames[117] = "objLaserOnH";
	global.__objectNames[118] = "objLaserOnV";
	global.__objectNames[119] = "objLaserSwitch";
	global.__objectNames[120] = "objCLaserOffH";
	global.__objectNames[121] = "objCLaserOffV";
	global.__objectNames[122] = "objCLaserOnH";
	global.__objectNames[123] = "objCLaserOnV";
	global.__objectNames[124] = "objCLaserSwitch";
	global.__objectNames[125] = "objKidBlockDown";
	global.__objectNames[126] = "objKidBlockUp";
	global.__objectNames[127] = "objRedBulletBill";
	global.__objectNames[128] = "objRedBulletCannon";
	global.__objectNames[129] = "objRedBulletHolder";
	global.__objectNames[130] = "objChompTrap";
	global.__objectNames[131] = "objChompy";
	global.__objectNames[132] = "objCherry";
	global.__objectNames[133] = "objCherryBounce";
	global.__objectNames[134] = "objCherryBounceRandom";
	global.__objectNames[135] = "objCherryBounceLat";
	global.__objectNames[136] = "objCherryBounceVert";
	global.__objectNames[137] = "objCherryCircle";
	global.__objectNames[138] = "objCherryNotDestroyOutsideRoom";
	global.__objectNames[139] = "objShurikenRotate";
	global.__objectNames[140] = "objThwomp";
	global.__objectNames[141] = "objKillerBlock";
	global.__objectNames[142] = "objMuncher";
	global.__objectNames[143] = "objSaw";
	global.__objectNames[144] = "objCherryEnemyTest";
	global.__objectNames[145] = "objCherryBossTest";
	global.__objectNames[146] = "objMiku";
	global.__objectNames[147] = "objCherryRandomCol";
	global.__objectNames[148] = "objCherryRandomColExplode";
	global.__objectNames[149] = "objCherryRandomColBounce";
	global.__objectNames[150] = "objTriggerManager";
	global.__objectNames[151] = "objTrigger";
	global.__objectNames[152] = "objTriggerButtonR";
	global.__objectNames[153] = "objTriggerButtonL";
	global.__objectNames[154] = "objFlipBlockDown";
	global.__objectNames[155] = "objFlipBlockUp";
	global.__objectNames[156] = "objHighGravityField";
	global.__objectNames[157] = "objHighSpeedField";
	global.__objectNames[158] = "objLowGravityField";
	global.__objectNames[159] = "objLowSpeedField";
	global.__objectNames[160] = "objAntiGravityField";
	global.__objectNames[161] = "objZeroGravityField";
	global.__objectNames[162] = "objRotateKidDown";
	global.__objectNames[163] = "objRotateKidUp";
	global.__objectNames[164] = "objSpinTransitionPlayer";
	global.__objectNames[165] = "objResetBeam";
	global.__objectNames[166] = "objHighGravBeam";
	global.__objectNames[167] = "objLowGravBeam";
	global.__objectNames[168] = "objSingleJumpBeam";
	global.__objectNames[169] = "objSpeedBeam";
	global.__objectNames[170] = "objVineR";
	global.__objectNames[171] = "objVineL";
	global.__objectNames[172] = "objRiseVineR";
	global.__objectNames[173] = "objRiseVineL";
	global.__objectNames[174] = "objIceVineR";
	global.__objectNames[175] = "objIceVineL";
	global.__objectNames[176] = "objFlipVineR";
	global.__objectNames[177] = "objFlipVineL";
	global.__objectNames[178] = "objStickyVineR";
	global.__objectNames[179] = "objStickyVineL";
	global.__objectNames[180] = "objLowGravVineR";
	global.__objectNames[181] = "objLowGravVineL";
	global.__objectNames[182] = "objTwinWhiteVineR";
	global.__objectNames[183] = "objTwinWhiteVineL";
	global.__objectNames[184] = "objTwinBlackVineR";
	global.__objectNames[185] = "objTwinBlackVineL";
	global.__objectNames[186] = "objSpeedVineR";
	global.__objectNames[187] = "objSpeedVineL";
	global.__objectNames[188] = "objFirePart";
	global.__objectNames[189] = "objShootRefresher";
	global.__objectNames[190] = "objShootRefresherL";
	global.__objectNames[191] = "objShootRefresherR";
	global.__objectNames[192] = "objToggleShootRefresherL";
	global.__objectNames[193] = "objToggleShootRefresherR";
	global.__objectNames[194] = "objDoubleJumpStar";
	global.__objectNames[195] = "objSingleJumpStar";
	global.__objectNames[196] = "objTripleJumpStar";
	global.__objectNames[197] = "objWindField";
	global.__objectNames[198] = "objMagnetField";
	global.__objectNames[199] = "objScreenWrap";
	global.__objectNames[200] = "objScreenWrapFull";
	global.__objectNames[201] = "objDotkidSwap";
	global.__objectNames[202] = "objRoomStartDotkid";
	global.__objectNames[203] = "objVCoinA";
	global.__objectNames[204] = "objVCoinB";
	global.__objectNames[205] = "objRoomStartVPlayer";
	global.__objectNames[206] = "objYoshi";
	global.__objectNames[207] = "objTelekidEnable";
	global.__objectNames[208] = "objTelekidDisable";
	global.__objectNames[209] = "objRoomStartTelekid";
	global.__objectNames[210] = "objHPbar";
	global.__objectNames[211] = "objHPbar2";
	global.__objectNames[212] = "objHPbg";
	global.__objectNames[213] = "objHPside";
	global.__objectNames[214] = "objKeypickControl";
	global.__objectNames[215] = "objKey";
	global.__objectNames[216] = "objMasterKey";
	global.__objectNames[217] = "objDoorBreak";
	global.__objectNames[218] = "objDoor1";
	global.__objectNames[219] = "objDoor2";
	global.__objectNames[220] = "objDoor3";
	global.__objectNames[221] = "objDoor4";
	global.__objectNames[222] = "objDoor6";
	global.__objectNames[223] = "objDoor8";
	global.__objectNames[224] = "objMasterDoor1";
	global.__objectNames[225] = "objMasterDoor2";
	global.__objectNames[226] = "objMasterDoor3";
	global.__objectNames[227] = "objMasterDoor4";
	global.__objectNames[228] = "objWater";
	global.__objectNames[229] = "objWater2";
	global.__objectNames[230] = "objWater3";
	global.__objectNames[231] = "objWaterUnrefreshing";
	global.__objectNames[232] = "objJumpRefresher";
	global.__objectNames[233] = "objBlockRefresher";
	global.__objectNames[234] = "objSign";
	global.__objectNames[235] = "objCouch";
	global.__objectNames[236] = "objLadder";
	global.__objectNames[237] = "objFloatingText";
	global.__objectNames[238] = "objGravityUp";
	global.__objectNames[239] = "objGravityDown";
	global.__objectNames[240] = "objGravityCoinUp";
	global.__objectNames[241] = "objGravityCoinDown";
	global.__objectNames[242] = "objSampleOscillator";
	global.__objectNames[243] = "objSaveMedium";
	global.__objectNames[244] = "objSave";
	global.__objectNames[245] = "objSaveVHard";
	global.__objectNames[246] = "objSaveMediumFlip";
	global.__objectNames[247] = "objSaveFlip";
	global.__objectNames[248] = "objSaveVHardFlip";
	global.__objectNames[249] = "objWarpStart";
	global.__objectNames[250] = "objRoomChanger";
	global.__objectNames[251] = "objWarp";
	global.__objectNames[252] = "objWarpNext";
	global.__objectNames[253] = "objOutsideRoomChanger";
	global.__objectNames[254] = "objColoredWarp";
	global.__objectNames[255] = "objSecretItem";
	global.__objectNames[256] = "objSecretIndicator";
	global.__objectNames[257] = "objBossItem";
	global.__objectNames[258] = "objBossIndicator";
	global.__objectNames[259] = "objGameClear";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
